name: linter

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pylint:
    name: pylint file before pushing to GitHub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # Step 1: Checkout the repository code
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
        # Step 2: Set up Python with the specified version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
        # Step 3: Install project dependencies and pylint
      - name: Check code quality
        run: |
          pylint --fail-under=8 $(git ls-files '*.py')
        # Step 4: Run pylint to check code quality
